Documentation about extending
BurdaMagazinOrg/thunder-documentation pull request #10
Opened 2017-04-11 15:14 UTC by goldquest

2017-04-19 15:36 UTC, mtodor requested changes

2017-04-19 15:36 UTC, mtodor commented on _includes/docs/extending/downloading.md
> +For example: `composer require drupal/entity_browser`
We should use same formatting for commands in our documentation. I have used:
```
# my_command
```
So it's always new line, way more distinguish from text and ready to copy paste. I would like to have one day something like this: https://www.tensorflow.org/tutorials/mandelbrot (so you can change code theme and also copy it). That would be nice. ;)

But until then, we just should think about best way to format command lines and use same formatting in documentation.

2017-04-19 15:36 UTC, mtodor commented on _includes/docs/extending/downloading.md
> +To install extensions via the command line, without using composer, you need to have [drush](http://www.drush.org/en/master/) installed. With this tool, you can manage your site in different ways, e.
I would keep docs not so technical, so that it's more accessible for other too. Maybe just few teaks here:
sql dumps -> database dumps

2017-04-19 15:36 UTC, mtodor commented on _includes/docs/extending/downloading.md
> +The command to download an extension is `drush dl [extension]`, which will download the latest recommended release for your Drupal version. Execute `drush help dl` for all available options.
It would be nice that you provide here same example as for composer:
For example:
```
drush dl entity_browser
```

2017-04-19 15:36 UTC, mtodor commented on _includes/docs/extending/downloading.md
> +### Drush make
Maybe we can think about removing this, since it's deprecated workflow.

2017-04-19 15:36 UTC, mtodor commented on _includes/docs/extending/downloading.md
> +First you have to enable the `Update Manager` module, by going to the `Extend` page, selecting the checkbox near it and clicking on `Install` at the bottom of the page. Then go to [http://yoursite.tl
Is it possible to somehow suppress these false links to be links. Maybe we can make italic or bold text. What do you thing?

2017-04-19 16:30 UTC, juliapradel requested changes
some correction on orthography (mostly commas), and three things which don't seem right: configuration with extend page, drush make, and UI

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/index.md
> +For information, on how to extend Drupal 8 in general, [refer to the Drupal 8 documentation](https://www.drupal.org/docs/8/extending-drupal-8)
Delete comma: "For information on how..., refer ...

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/finding-extensions.md
> +You can find many extension on [Drupal.org](https://www.drupal.org/download).
many extensionS

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/finding-extensions.md
> +If you know what module you want, it is often fastest to just google it, adding `drupal` to the search.
Better: "to do a search on Google, adding..."

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +Depending on, if you have a composer, command-line, drush-make or UI based workflow, downloading of themes and modules differs.
Better: "Depending on whether you have ..., the download process of ..."

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +If you have composer installed, go to the root of your site (here there should be a `composer.json` file) and install modules by typing `composer require drupal/[shortname of module]` into the comman
Delete "here": "site (there should..."

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +To install extensions via the command line, without using composer, you need to have [drush](http://www.drush.org/en/master/) installed. With this tool, you can manage your site in different ways, e.
Add comma: "cache, and also..."

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +The drush-make workflow was the most used one, which involved not checking in all your dependencies into your repository,
Don't understand this sentence. Plus, you should decide if it's "drush make" or "drush-make"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +First you have to enable the `Update Manager` module, by going to the `Extend` page, selecting the checkbox near it and clicking on `Install` at the bottom of the page. Then go to [http://yoursite.tl
Delete comma: "module by going"
Add comma: "near it, and clicking"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +Here you can either paste a URL to an archival file on drupal.org, or browse your computer to select one.
Correct: "an URL"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +You can also install modules and themes via the UI, but we _strongly_ advise against that.
Why is this text about installing part of the chapter "Downloading"? And why do you strongly disadvise to use it here, but not when installing?

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/installing.md
> +### UI
I would use the same order as above, first command line, second UI

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/installing.md
> +To actually install a module, select the checkbox next to it, scroll to the bottom and click `Install`. You might be warned, that another module needs to be enabled, because it is required for the mo
Add comma: "to the bottom, and click"
Delete comma: "warned that another"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/installing.md
> +Here you can scroll to the theme, you would like to install and click on `Install`, to install it, or click on `Install and set as default`, to use the theme for your site, after installing it.
Add comma: "like to install, and click"
Delete commas: "'Install' to install it, or on 'Install and...' to use the theme for your site after installing it"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/installing.md
> +At the bottom of this page, you can also decide, which installed theme you would like to use as admin theme.
Delete comma: "decide which installed"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/configuring.md
> +Also the documentation of the module on [http://drupal.org]() should point to the correct place.
Add comma: "Also, the documentation..."

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/configuring.md
> +Note, that not all modules have configuration pages.
Delete comma: "Note that not"

2017-04-19 16:30 UTC, juliapradel commented on _includes/docs/extending/configuring.md
> +you can find a `Configure` link, after expanding the module description, by clicking on it.
I don't get this: How can I find the link by clicking on it? Doesn't sound right.

2017-04-20 09:47 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +For example: `composer require drupal/entity_browser`
yes. I will also activate githubs default syntax highlighting, called rouge: http://rouge.jneen.net/

2017-04-20 09:51 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +First you have to enable the `Update Manager` module, by going to the `Extend` page, selecting the checkbox near it and clicking on `Install` at the bottom of the page. Then go to [http://yoursite.tl
I'm also not satisfied with the links. I tried, italic and bold, but was also not happy.
Maybe we just do normal backticks?

2017-04-20 09:51 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +First you have to enable the `Update Manager` module, by going to the `Extend` page, selecting the checkbox near it and clicking on `Install` at the bottom of the page. Then go to [http://yoursite.tl
also we should commit to a default way domain, when providing example links.
I think https://example.org would be good.

2017-04-20 12:45 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +To install extensions via the command line, without using composer, you need to have [drush](http://www.drush.org/en/master/) installed. With this tool, you can manage your site in different ways, e.
I would prefer not having this oxford comma

2017-04-20 12:47 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +First you have to enable the `Update Manager` module, by going to the `Extend` page, selecting the checkbox near it and clicking on `Install` at the bottom of the page. Then go to [http://yoursite.tl
again, would prefer no oxford comma

2017-04-20 12:49 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +Here you can either paste a URL to an archival file on drupal.org, or browse your computer to select one.
Sounds wrong

2017-04-20 12:50 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +Here you can either paste a URL to an archival file on drupal.org, or browse your computer to select one.
Others seem to agree ;)
https://answers.yahoo.com/question/index?qid=20071129210200AAOm7FF
http://itknowledgeexchange.techtarget.com/writing-for-business/which-is-correct-a-url-or-an-url/

2017-04-20 13:01 UTC, goldquest commented on _includes/docs/extending/installing.md
> +### UI
Hmm, the thing is, that while downloading is discouraged via the UI, Installing via UI is encouraged

2017-04-20 13:02 UTC, goldquest commented on _includes/docs/extending/installing.md
> +To actually install a module, select the checkbox next to it, scroll to the bottom and click `Install`. You might be warned, that another module needs to be enabled, because it is required for the mo
oxford, see above

2017-04-20 13:24 UTC, juliapradel commented on _includes/docs/extending/installing.md
> +### UI
Maybe you could clarify that?

2017-04-20 13:24 UTC, juliapradel commented on _includes/docs/extending/index.md
> +For information, on how to extend Drupal 8 in general, [refer to the Drupal 8 documentation](https://www.drupal.org/docs/8/extending-drupal-8)
Das ist kein Oxford Comma und muss meiner Meinung nach WIRKLICH weg

2017-04-20 13:40 UTC, mtodor approved these changes

2017-04-20 13:48 UTC, juliapradel requested changes

2017-04-20 13:48 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +Depending on, whether you have a composer, command-line, drush-make or UI based workflow, the method of downloading themes and modules differs.
Delete comma: "Depending on whether you..:"

2017-04-20 13:48 UTC, juliapradel commented on _includes/docs/extending/downloading.md
> +You can also install modules and themes via the UI, but we _strongly_ advise against that.
Do you maybe mean "download modules and themes"?

2017-04-20 13:54 UTC, goldquest commented on _includes/docs/extending/downloading.md
> +You can also install modules and themes via the UI, but we _strongly_ advise against that.
yeah, if you use this functionality, they get downloaded _and_ installed

2017-04-20 13:56 UTC, goldquest commented on _includes/docs/extending/installing.md
> +### UI
I think it is clarified, by stating in the downloading part, that only downloading via UI is discouraged.

2017-04-20 14:06 UTC, juliapradel approved these changes

2017-04-20 14:21 UTC, merged